#!/usr/bin/env python3
"""
Generate autoGEMM-style NEON assembly micro-kernels for dnnopt.
Simplified version focusing on 4x16 and 6x16 tiles.

Based on autoGEMM (SC'24): https://github.com/wudu98/autoGEMM
This script generates inline assembly that can be embedded in C++ code.
"""

import sys

# ARM NEON constants
SIMD_LANE = 4  # floats per vector register
RESERVED_REG = 6  # x0-x5 for input/output

def gen_prologue(Mr, Nr, K_unroll=4):
    """Generate assembly prologue with pointer setup and prefetch."""

    nr_vec = Nr // SIMD_LANE  # Number of vector registers for N dimension

    code = f"""
// Auto-generated NEON assembly kernel for {Mr}x{Nr} tile
// Generated by: tools/gen_asm_kernel.py
// K-unroll: {K_unroll}

asm volatile (
    // Prefetch A and B into L1 cache
    "prfm    PLDL1KEEP, [%[A], #64]        \\n"
    "prfm    PLDL1KEEP, [%[B], #64]        \\n"

    // Scale strides: lda *= 4, ldb *= 8 (for 2x K-unroll), ldc *= 4
    "lsl     %[lda], %[lda], #2            \\n"
    "lsl     %[ldb], %[ldb], #3            \\n"
    "lsl     %[ldc], %[ldc], #2            \\n"

    // Setup row pointers for A (M rows)
    "mov     x21, %[A]                     \\n"
"""

    # Add row pointer setup for each M row
    for i in range(1, Mr):
        code += f'    "add     x{RESERVED_REG + 12 + i}, x21, %[lda], lsl #{i.bit_length() - 1} \\n"\n'

    # Setup C row pointers
    code += '    "mov     x24, %[C]                     \\n"\n'
    for i in range(1, Mr):
        code += f'    "add     x{RESERVED_REG + i}, x24, %[ldc], lsl #{i.bit_length() - 1} \\n"\n'

    return code


def gen_k_loop(Mr, Nr, K_unroll=4):
    """Generate main K loop with 2x unrolling and accumulator updates."""

    nr_vec = Nr // SIMD_LANE

    code = f"""
    // Main K loop (2x unrolled)
    "mov     x27, #%(K_unroll // 2)              \\n"
    "subs    x27, x27, #1                    \\n"
    "b       2f                              \\n"
  "1:                                        \\n"
"""

    # Generate K loop body (will be filled by gen_kernel_body)
    code += gen_kernel_body(Mr, Nr, is_main=True)

    code += f"""
  "2:                                        \\n"
    "beq     3f                              \\n"
    "subs    x27, x27, #1                    \\n"
    "b       1b                              \\n"
  "3:                                        \\n"

    // K tail handling (if K is odd)
    // TODO: Add K tail code
"""

    return code


def gen_kernel_body(Mr, Nr, is_main=False):
    """Generate kernel body with FMLA operations and register management."""

    nr_vec = Nr // SIMD_LANE
    total_acc = Mr * nr_vec

    code = ""

    # Initialize accumulators (only once at start)
    if not is_main:
        for i in range(total_acc):
            reg_id = 32 - total_acc + i  # Use high register numbers for acc
            code += f'    "fmov.d v{reg_id}, #0.0               \\n"\n'

    # Generate compute pattern for 2 K iterations
    for k_iter in range(2):
        code += f"\n    // K iteration {k_iter}\n"

        # Load B panel (nr_vec vectors)
        for j in range(nr_vec):
            # Alternating between two registers to hide latency
            b_reg = 16 + (j % 4)
            code += f'    "ldr     q{b_reg}, [x22], #16            \\n"\n'

        # For each M row, broadcast A scalar and compute FMLA
        for i in range(Mr):
            a_ptr = x21 + i * lda (need to track this properly)

            for j in range(nr_vec):
                acc_reg = 32 - total_acc + i * nr_vec + j
                b_reg = 16 + (j % 4)

                # vfmaq_n_f32 equivalent in assembly
                code += f'    "fmla    v{acc_reg}.4s, v{b_reg}.4s, v{{A_scalar}}.s[{k_iter}] \\n"\n'

    return code


def gen_epilogue(Mr, Nr):
    """Generate store epilogue with alpha scaling."""

    nr_vec = Nr // SIMD_LANE
    total_acc = Mr * nr_vec

    code = """
    // Scale accumulators by alpha and store to C
"""

    for i in range(Mr):
        for j in range(nr_vec):
            acc_reg = 32 - total_acc + i * nr_vec + j
            c_ptr = f"x{RESERVED_REG + i}" if i > 0 else "x24"
            code += f'    "str     q{acc_reg}, [{c_ptr}, #{j * 16}]  \\n"\n'

    return code


def gen_full_kernel(Mr, Nr, K_unroll=4):
    """Generate complete kernel function."""

    code = f"""static inline void gemm_kernel_{Mr}x{Nr}_asm(int K,
                                      const float* A, int lda,
                                      const float* B, int ldb,
                                      float* C, int ldc,
                                      float alpha, float beta) {{
    // Register allocations:
    // - x0-x5: function arguments
    // - x6-x17: row pointers for A and C
    // - x21: A base pointer
    // - x22, x23: B pointers (ping-pong)
    // - x24: C base pointer
    // - x25-x27: loop counters
    // - v0-v15: B panel and temporaries
    // - v16-v31: accumulators (Mr × Nr/4 vectors)

"""

    # Generate assembly block
    asm_code = gen_prologue(Mr, Nr, K_unroll)
    asm_code += gen_k_loop(Mr, Nr, K_unroll)
    asm_code += gen_epilogue(Mr, Nr)

    # Add clobbers and output operands
    asm_code += """
    : [A] "+r" (A), [B] "+r" (B), [C] "+r" (C),
      [lda] "+r" (lda), [ldb] "+r" (ldb), [ldc] "+r" (ldc)
    :
    : "cc", "memory"
"""

    for i in range(6, 32):
        if i != 18:
            asm_code += f', "x{i}"'
    for i in range(32):
        asm_code += f', "v{i}"'

    asm_code += "\\n);\n}\n"

    code += asm_code
    return code


def gen_test_harness():
    """Generate test code for benchmarking."""

    return """
// Test harness
int main() {
    const int M = 4, N = 16, K = 64;
    const int lda = K, ldb = N, ldc = N;

    float* A = (float*)aligned_alloc(64, M * lda * sizeof(float));
    float* B = (float*)aligned_alloc(64, K * ldb * sizeof(float));
    float* C = (float*)aligned_alloc(64, M * ldc * sizeof(float));

    // Initialize with random data
    for (int i = 0; i < M * lda; i++) A[i] = (float)rand() / RAND_MAX;
    for (int i = 0; i < K * ldb; i++) B[i] = (float)rand() / RAND_MAX;
    memset(C, 0, M * ldc * sizeof(float));

    // Warmup
    for (int i = 0; i < 100; i++) {
        gemm_kernel_4x16_asm(K, A, lda, B, ldb, C, ldc, 1.0f, 0.0f);
    }

    // Benchmark
    auto start = std::chrono::high_resolution_clock::now();
    const int iterations = 10000;
    for (int i = 0; i < iterations; i++) {
        gemm_kernel_4x16_asm(K, A, lda, B, ldb, C, ldc, 1.0f, 0.0f);
    }
    auto end = std::chrono::high_resolution_clock::now();

    double elapsed = std::chrono::duration<double>(end - start).count();
    double gflops = 2.0 * M * N * K * iterations / elapsed / 1e9;

    printf("4x16 ASM kernel: %.2f GFLOPS\\n", gflops);

    free(A); free(B); free(C);
    return 0;
}
"""


if __name__ == "__main__":
    # Generate 4x16 kernel (most common case)
    Mr, Nr = 4, 16
    print(f"// Auto-generated {Mr}x{Nr} NEON assembly kernel")
    print(f"// Mr={Mr}, Nr={Nr}, K-unroll=4")
    print()

    kernel_code = gen_full_kernel(Mr, Nr, K_unroll=4)
    print(kernel_code)

    # Optionally generate test harness
    if "--with-test" in sys.argv:
        print(gen_test_harness())
